export const queryKeys = {
  vehicles: ["vehicles"] as const,
  vehicle: (id: string) => ["vehicles", id] as const,
  kpiSummary: ["kpi-summary"] as const,
  drivers: ["drivers"] as const,
  alerts: ["alerts"] as const,
  trips: (vehicleId?: string) => ["trips", vehicleId ?? "all"] as const,
  trip: (id: string) => ["trip", id] as const,
  geofences: ["geofences"] as const,
  groups: ["groups"] as const,
  commandLog: ["command-log"] as const,
  users: ["users"] as const,
  report: (type: string) => ["report", type] as const,
  devices: ["devices"] as const,
  financials: ["financials"] as const,
  fuelOdometerEntries: ["fuel-odometer-entries"] as const,
  insurancePolicies: ["insurance-policies"] as const,
  scorecards: ["scorecards"] as const,
  billingCycle: ["billing-cycle"] as const,
  paymentMethods: ["payment-methods"] as const,
  invoices: ["invoices"] as const,
  usageLedger: ["usage-ledger"] as const,
  shifts: ["shifts"] as const,
};
