export const routes = {
  login: "/login",
  dashboard: "/dashboard",
  liveMap: "/live-map",
  tracking: (vehicleId = ":vehicleId") => `/tracking/${vehicleId}`,
  tripHistory: (tripId = ":tripId") => `/trips/${tripId}`,
  fuelLog: "/fuel-log",
  timeline: "/timeline",
  reports: "/reports",
  reportResults: "/reports/results",
  insurance: "/insurance",
  events: "/events",
  financials: "/financials",
  stats: "/vehicles",
  drivers: "/drivers",
  geofences: "/geofences",
  groups: "/groups",
  addDevice: "/add-device",
  devices: "/devices",
  profile: "/profile",
  subscription: "/subscription",
  billing: "/billing",
  cancelPlan: "/cancel-plan",
  users: "/users",
  // NEW: live tracking for customers (public)
  liveTracking: (trackingId = ":trackingId") => `/track/${trackingId}`,
  // NEW: 3D trip replay
  tripReplay: (tripId = ":tripId") => `/replay/${tripId}`,
} as const;
