import {
  Broadcast,
  ClockCounterClockwise,
  CreditCard,
  FileText,
  MapTrifold,
  Path,
  Plus,
  Polygon,
  Receipt,
  ShieldStar,
  SquaresFour,
  Stack,
  TrendUp,
  Truck,
  UserCircle,
  Users,
  UsersThree,
  WarningCircle,
} from "@phosphor-icons/react";
import type { NavEntry } from "@navyug/ui";
import { routes } from "./routes";

export const navEntries: NavEntry[] = [
  { type: "section", label: "PLAN" },
  { type: "item", id: "dashboard", label: "Dashboard", icon: <SquaresFour weight="fill" />, href: routes.dashboard },
  { type: "section", label: "TRACK" },
  { type: "item", id: "livemap", label: "Live Map", icon: <MapTrifold weight="fill" />, href: routes.liveMap },
  { type: "item", id: "fuellog", label: "Trips & Fuel Log", icon: <Path weight="fill" />, href: routes.fuelLog },
  { type: "item", id: "timeline", label: "Vehicle Timeline", icon: <ClockCounterClockwise weight="fill" />, href: routes.timeline },
  { type: "section", label: "ANALYSE" },
  { type: "item", id: "reports", label: "Reports", icon: <FileText weight="fill" />, href: routes.reports },
  { type: "item", id: "insurance", label: "Insurance", icon: <ShieldStar weight="fill" />, href: routes.insurance },
  { type: "item", id: "events", label: "Alerts", icon: <WarningCircle weight="fill" />, href: routes.events },
  { type: "item", id: "financials", label: "Financials", icon: <TrendUp weight="fill" />, href: routes.financials },
  { type: "section", label: "INSIGHTS" },
  { type: "item", id: "stats", label: "Vehicles", icon: <Truck weight="fill" />, href: routes.stats },
  { type: "item", id: "drivers", label: "Drivers", icon: <Users weight="fill" />, href: routes.drivers },
  { type: "item", id: "geofence", label: "Geofence", icon: <Polygon weight="fill" />, href: routes.geofences },
  { type: "item", id: "groups", label: "Groups", icon: <Stack weight="fill" />, href: routes.groups },
  { type: "section", label: "DEVICES" },
  { type: "item", id: "adddevice", label: "Add Device", icon: <Plus weight="bold" />, href: routes.addDevice },
  { type: "item", id: "devices", label: "Device Commands", icon: <Broadcast weight="fill" />, href: routes.devices },
  { type: "section", label: "SETTINGS" },
  { type: "item", id: "profile", label: "Profile", icon: <UserCircle weight="fill" />, href: routes.profile },
  { type: "item", id: "subscription", label: "Subscription", icon: <CreditCard weight="fill" />, href: routes.subscription },
  { type: "item", id: "billing", label: "Billing", icon: <Receipt weight="fill" />, href: routes.billing },
  { type: "item", id: "users", label: "Users", icon: <UsersThree weight="fill" />, href: routes.users },
];

export const pageTitles: Record<string, string> = {
  dashboard: "Dashboard",
  livemap: "Live Map",
  tracking: "Real Time Tracking",
  trips: "Trip History",
  fuellog: "Trips & Fuel Log",
  timeline: "Vehicle Timeline",
  stats: "Vehicle Statistics",
  events: "Event Timeline",
  reports: "Vehicle Reports",
  "reports-results": "Report Results",
  insurance: "Insurance",
  financials: "Financials Overview",
  drivers: "Drivers",
  geofence: "Geofence",
  groups: "Groups",
  adddevice: "Add Devices",
  devices: "Device Commands",
  profile: "Profile",
  subscription: "Subscription",
  billing: "Billing & Payments",
  cancelplan: "Cancel Plan",
  users: "Users",
};
